server:
  port: 8080

agent:
  url: ${AGENT_URL:http://localhost:8000}

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER:https://dev-3lau552vpf734fpb.us.auth0.com/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth0:
  domain: ${AUTH0_DOMAIN:dev-3lau552vpf734fpb.us.auth0.com}
  audience: ${AUTH0_AUDIENCE:https://api.medical-insights.com}